### ISSUE TITLE
Add ASN.1 types required for X.509 certificates (large integers, bit strings, OIDs, etc)

### ISSUE THREAD

**Issue by awakecoding** [KizzyCode/serde_asn1_der-rust#1]
This really is a large feature request, but I just found this project today, and it looks like it has the potential of eventually serializing/deserializing common ASN.1 DER structures used in PKI such as X.509 certificates, RSA key pairs, certificate signing requests, OCSP requests/responses, etc.

Is this one of the goals of this project, or was it started with other use cases in mind?

Being able to safely encode/decode these data structures in pure Rust with something like serde is something that would be extremely valuable for crypto. This is the kind of project I think we could sponsor if you're interested.

**Comment by KizzyCode** [comment]
Well the project was not started with this feature in mind; the goal was to (de-)serialize custom data structures. However if those data-types are not too complex (and if no large-integer arithmetic is required) it should be possible to implement those types (honestly I never looked into them because I didn't need them).

**Comment by awakecoding** [comment]
Thanks for the quick reply - unfortunately, X.509 and PKI-related data types use all of the complex ASN.1 data types :/ I've seen a couple of ASN.1 Rust projects deal with just the basic types, but the real deal would be to handle the complex ones. I'm thinking something serde-based like this project could be the right approach, as opposed to ASN.1 compilers / code generators.

**Comment by KizzyCode** [comment]
I also have written an [`serde_asn1_der`-crate](https://crates.io/crates/serde_asn1_der), maybe this could serve as template…

**Comment by awakecoding** [comment]
I was curious to give it a shot with one of the simplest data structures used in PKI: the OCSP Request/Response structures used to check for certificate revocation status. I got almost all of it working except for the OBJECT IDENTIFIER structure which would need to be implemented: https://github.com/Devolutions/serde_asn1_der/blob/ocsp/examples/ocsp.rs

The OCSPRequest structure is pretty much SEQUENCE inside SEQUENCE with a lot of optional fields, a few hashes and an algorithm identifier (in my case, I've used a sample with sha1). This crate works very well! Adding OBJECT IDENTIFIER support should not be too bad: https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-object-identifier

Now if we could get support for large integers (very common for keys), bit strings and a few other data types I think there's a bunch of the common PKI data types that could be easily implemented :) I'm very hopeful about this.

**Comment by awakecoding** [comment]
@KizzyCode I've discussed it with my team, and we'll try adding support for the required ASN.1 data types such that we can use this crate to encode/decode common PKI-related data types. We'll try to keep it clean such that we can submit proper PRs afterwards. External data types like OIDs (using the oid crate) and large integers will be enabled as features.

**Comment by KizzyCode** [comment]
Im currently wondering if it wouldn’t be better to create an extension crate (e.g. `asn1_der_pki`). This would allow to add all complex PKI types together with some PKI-only helpers while keeping the basic crate small… What do you think?

**Comment by awakecoding** [comment]
I'm thinking that since PKI requires a lot of the more complex ASN.1 types, but that these ASN.1 types are not PKI-specific, the best would be to add support for all ASN.1 types in this case but put some of them behind feature gates (OIDs, large integers, etc). PKI data types defined using those complex ASN.1 data types would never be in the core crate, but in external projects depending on this crate. What do you think?

**Comment by KizzyCode** [comment]
Yeah; I think (de-)serialization and some basic representation fits perfectly into the core crate.  
I was wondering about the „working with types“-part.

I thought about sth. like this (e.g. for OIDs): implement a basic `OID` type which is (de-)serializable and has a *simple* internal representation. 
Now you could create an `asn1_der_pki`-crate which maps the simple OID type to a implementation useful for PKI (e.g. the `oid` crate).
This separation would allow you to map basic types to _multiple_ context specific implementations. For OIDs this might not be very important, but other types like bignums or bitstreams may be used in various multiple contexts and require different implementations/crates.

I‘m a currently a little bit reluctant to add feature gates for types to the core crate, because either those types are generally useful (then they should be generally available in the core crate and also not tied to any specific implementation) – or they are not (then they should be implemented in another crate on top of the `DerObject` type).
However this are just some quick thoughts 😊

**Comment by ghost** [comment]
Hi!

Thanks for your thoughts!
We decided to start maintaining a fork for our immediate needs because it's more straightforward for our use-cases.
You probably won't want to merge because it adds dependencies to specific implementations for aforementioned types (behind a feature gate).
You might however want to have a look at this commit: https://github.com/Devolutions/serde_asn1_der/commit/a7927e35bd3a21ed40f6ec83603c07f600d479b0
It fixes an issue for lengths written on multiple bytes (check new tests in the same commit).

Cheers!

**Comment by KizzyCode** [comment]
Oh damn, thank you very much! I should have had a test case for this 🤦🏻‍♀️
Your work on the fork is pretty cool and I'll make sure to take a look at it regularly. 👍🏻

**Comment by hug-dev** [comment]
Hi!
We would also be very interested in the support of big integers to be able to decode/encode RSA public keys, ie the following sequence:
```
RSAPublicKey ::= SEQUENCE {
    modulus           INTEGER,  -- n
    publicExponent    INTEGER   -- e
}
```
Any chance that could be part of this crate as well 😋 ? The fork mentionned above seems to support it already with Devolutions/serde_asn1_der@2f7160f0c997ae095c5dac8564409a0ae22b914b so I think we are going to use that for now but having common crate(s) would be nice indeed!

**Comment by KizzyCode** [comment]
Yes, I think I will implement a generic representation of BigInts and some other types. Then you can easily cast them into your specific implementation :)

**Comment by awakecoding** [comment]
@hug-dev @KizzyCode we managed to implement common PKI data types such as X.509 certificates, pkcs#10 certificate signing requests, RSA public/private keys, OCSP request/response using our fork. We already have made very significant changes, so it may make more sense to make a spin-off project rather than try and get it merged back (unless you wish to take such large changes back). We are currently reworking an internal PKI component that leverages the modified ASN.1 library, once we remove a dependency on mbedtls we should be able to make it open source. This component will contain PKI data type definitions and manage to encode/decode all of them without an external C library such as OpenSSL or mbedtls.

**Comment by ghost** [comment]
@hug-dev I'm happy our fork can help you for the time being :+1: 
I recommend you to add a specific commit (using "rev" in your Cargo.toml) for now as we might push breaking changes in the near future (specifically for the big integer support). As pointed out by KizzyCode a basic BigInt representation easily convertible is what we really want.

**Comment by hug-dev** [comment]
Great! Yes, I think pulling a specific commit number is definitely a good idea. I will watch this space when support for BigInt is there 😃

**Comment by awakecoding** [comment]
@KizzyCode @hug-dev we intend to take this project in a totally different direction, trying to eventually support all advanced ASN.1 types and potentially more than just DER (BER, PER, maybe even JER if we feel wild enough). We're about to cleanup our fork and find a new name for publishing on crates.io. If you feel like our fork is going in the same direction as this project, let me know, but my understanding is we'd be better off going our own way, no hard feelings.

This being said, I would have one small request: would it be possible to let us relicense the original source code from Apache/BSD to Apache/MIT? We don't have an issue with BSD, it would just be to match the dual licensing used in most of our other projects, and wouldn't affect attribution (we definitely won't hide the fact that our fork is based on this project).

Thanks a lot!

**Comment by hug-dev** [comment]
Exciting! For us the change of license is not a problem as the new license would still be compatible with our project's.

**Comment by KizzyCode** [comment]
@awakecoding Yeah; this is no problem. I don't have any issues with Apache/MIT, feel free to relicense your fork to Apache/MIT 👍🏻

**Comment by awakecoding** [comment]
@KizzyCode thanks a lot, I'll let you know when we publish the project under a new name :)

**Comment by ghost** [comment]
@hug-dev @KizzyCode 
Hi! We finally published our fork on crates.io under the name [picky-asn1-der](https://crates.io/crates/picky-asn1-der).  Of course KizzyCode is in the author section of the Cargo.toml and this project is mentioned  in the README! :slightly_smiling_face: 
The crate containing more advanced ASN.1 wrappers is published as [picky-asn1](https://crates.io/crates/picky-asn1) in an encoding-independent fashion should we consider supporting BER as well. The picky-asn1-der depend on it.

**Comment by hug-dev** [comment]
@bcortier-devolutions Congrats!! We will switch to it as per parallaxsecond/parsec#84
