### ISSUE TITLE
Cannot compile! 1.43

### ISSUE THREAD

**Issue by lygz5016** [KizzyCode/serde_asn1_der-rust#3]
error msg:
```
error[E0599]: no method named `encode` found for type `i8` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:153:8
    |
153 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i8`

error[E0599]: no method named `encode` found for type `i16` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:156:8
    |
156 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i16`

error[E0599]: no method named `encode` found for type `i32` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:159:8
    |
159 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i32`

error[E0599]: no method named `encode` found for type `i64` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:162:8
    |
162 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i64`

error[E0599]: no method named `encode` found for type `i128` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:166:8
    |
166 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i128`

error[E0599]: no function or associated item named `load` found for type `i8` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:70:16
   |
70 |         let i8 = i8::load(self.object).propagate(e!("Failed to load object"))?;
   |                      ^^^^ function or associated item not found in `i8`

error[E0599]: no function or associated item named `load` found for type `i16` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:74:18
   |
74 |         let i16 = i16::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i16`

error[E0599]: no function or associated item named `load` found for type `i32` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:78:18
   |
78 |         let i32 = i32::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i32`

error[E0599]: no function or associated item named `load` found for type `i64` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:82:18
   |
82 |         let i64 = i64::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i64`

error[E0599]: no function or associated item named `load` found for type `i128` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:87:20
   |
87 |         let i128 = i128::load(self.object).propagate(e!("Failed to load object"))?;
   |                          ^^^^ function or associated item not found in `i128`

error: aborting due to 10 previous errors

```

**Comment by lygz5016** [comment]
error[E0599]: no method named `encode` found for type `i8` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:153:8
    |
153 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i8`

error[E0599]: no method named `encode` found for type `i16` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:156:8
    |
156 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i16`

error[E0599]: no method named `encode` found for type `i32` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:159:8
    |
159 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i32`

error[E0599]: no method named `encode` found for type `i64` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:162:8
    |
162 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i64`

error[E0599]: no method named `encode` found for type `i128` in the current scope
   --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\ser.rs:166:8
    |
166 |         Ok(v.encode(&mut self.sink).propagate(e!("Failed to write integer"))?)
    |              ^^^^^^ method not found in `i128`

error[E0599]: no function or associated item named `load` found for type `i8` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:70:16
   |
70 |         let i8 = i8::load(self.object).propagate(e!("Failed to load object"))?;
   |                      ^^^^ function or associated item not found in `i8`

error[E0599]: no function or associated item named `load` found for type `i16` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:74:18
   |
74 |         let i16 = i16::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i16`

error[E0599]: no function or associated item named `load` found for type `i32` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:78:18
   |
78 |         let i32 = i32::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i32`

error[E0599]: no function or associated item named `load` found for type `i64` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:82:18
   |
82 |         let i64 = i64::load(self.object).propagate(e!("Failed to load object"))?;
   |                        ^^^^ function or associated item not found in `i64`

error[E0599]: no function or associated item named `load` found for type `i128` in the current scope
  --> C:\Users\lygz_\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_asn1_der-0.7.0\src\de.rs:87:20
   |
87 |         let i128 = i128::load(self.object).propagate(e!("Failed to load object"))?;
   |                          ^^^^ function or associated item not found in `i128`

error: aborting due to 10 previous errors

**Comment by KizzyCode** [comment]
Dang! I temporarily removed the signed integer support from `asn1_der` and forgot to publish the updated `serde_asn1_der`-version… The updated version (0.7.1) is now public.

I'm really sorry; thank you for the issue!!
